# Generated by Django 5.2.8 on 2025-12-01 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao_produto', models.TextField(blank=True, verbose_name='Descrição')),
                ('estoque_atual_produto', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo_produto', models.IntegerField(default=1, verbose_name='Estoque Mínimo')),
                ('unidade_medida_produto', models.CharField(default='unidade', max_length=20, verbose_name='Unidade de Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7, verbose_name='Tipo de Movimentação')),
                ('quantidade_movimentacao', models.IntegerField(verbose_name='Quantidade')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao_movimentacao', models.TextField(blank=True, verbose_name='Observação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='api.produto', verbose_name='Produto')),
            ],
        ),
    ]
